site: 0o3q
title: 0o3q
greetings: 0o3q's Blog 👋
description: >-
  그냥 대학생의 보안 블로그
lang: ko
timezone:  Asia/Seoul
repo: 0o3q/0o3q.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: 0o3q
  bio: Studying Security
  userpicture: 
  username: 0o3q # general username
  github: 0o3q # github username
  twitter: mingw03 # twitter username
  email: minkyu2045@ajou.ac.kr # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://0o3q.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

pagination: 10
pagination_path: "/page:num/"

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-toc

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


